#! /usr/bin/env bash

# docker build --build-arg user=$USER -t devian . && docker run -v $HOME:/home/$USER -it devian
docker build --build-arg user=$USER -t devian . && docker run -v $HOME:/home/$USER -it devian
