#! /usr/bin/env bash

docker build -t scibox . && \
  docker run -i -t -p 8888:8888 -v $HOME:/home/$USER scibox /bin/bash \
    -c "/opt/conda/bin/conda install jupyter -y --quiet &&
          /opt/conda/bin/jupyter notebook --notebook-dir=/home/$USER/Development \
                                          --ip='*' \
                                          --port=8888 \
                                          --no-browser \
                                          --allow-root"
