#! /usr/bin/env bash

docker build -t scibox . && \
  docker run -i -t -p 3030:3030 -v $HOME:/home/$USER scibox /bin/bash \
    -c "/opt/conda/bin/jupyter notebook --notebook-dir=/home/$USER/Development \
                                        --ip='*' \
                                        --port=3030 \
                                        --no-browser \
                                        --allow-root"
